const categories = [
  {
    name: 'Audio & Acoustics',
    slug: 'audio-acoustics',
    description: 'High-fidelity spatial audio headsets, wireless earbuds, and studio monitors.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    isFeatured: true,
  },
  {
    name: 'Smart Wearables',
    slug: 'smart-wearables',
    description: 'Advanced fitness trackers, AMOLED smartwatches, and biometric wearables.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    isFeatured: true,
  },
  {
    name: 'Smartphones & Mobile',
    slug: 'smartphones-mobile',
    description: 'Flagship smartphones with pro cameras, high refresh displays, and fast charging.',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
    isFeatured: true,
  },
  {
    name: 'Gaming & Computing',
    slug: 'gaming-computing',
    description: 'Ergonomic gaming gear, custom mechanical keyboards, and precision controllers.',
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800',
    isFeatured: true,
  },
  {
    name: 'Footwear & Performance',
    slug: 'footwear-performance',
    description: 'Engineered running shoes, lifestyle sneakers, and active footwear.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    isFeatured: true,
  },
  {
    name: 'Smart Home & Living',
    slug: 'smart-home-living',
    description: 'Ergonomic task chairs, ambient smart lighting, and high-tech workspace gear.',
    image: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?w=800',
    isFeatured: true,
  },
];

const products = [
  // Category 1: Audio & Acoustics (Products 1-5)
  {
    name: 'Apex ANC Wireless Headphones',
    description: 'Industry-leading noise cancellation headset with 40mm beryllium drivers, 40-hour battery life, spatial audio head tracking, and ultra-soft memory foam earcups.',
    price: 349.99,
    discountPercentage: 15,
    categoryName: 'Audio & Acoustics',
    brand: 'AeroSound',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
    ],
    specifications: [
      { key: 'Driver Size', value: '40mm Beryllium' },
      { key: 'Battery Life', value: '40 Hours (ANC On)' },
      { key: 'Connectivity', value: 'Bluetooth 5.3 & 3.5mm AUX' },
      { key: 'Weight', value: '254g' },
    ],
    stock: 25,
    model3D: { type: 'headphones', color: '#0f172a', accentColor: '#38bdf8', scale: 1.2 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Pulse Pro True Wireless Earbuds',
    description: 'Ultra-compact earbuds featuring active noise cancellation, transparency mode, IPX7 water resistance, and wireless charging case.',
    price: 189.99,
    discountPercentage: 10,
    categoryName: 'Audio & Acoustics',
    brand: 'AeroSound',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800',
    ],
    specifications: [
      { key: 'Water Rating', value: 'IPX7 Waterproof' },
      { key: 'Playtime', value: '8 Hours + 24 Hours Case' },
      { key: 'Microphones', value: 'Quad beamforming mics' },
    ],
    stock: 40,
    model3D: { type: 'headphones', color: '#6366f1', accentColor: '#a855f7', scale: 1.0 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Studio Master Reference Monitor Speakers',
    description: 'Professional bi-amplified studio monitor pair with Kevlar woofers, silk dome tweeters, and room acoustic optimization controls.',
    price: 499.00,
    discountPercentage: 0,
    categoryName: 'Audio & Acoustics',
    brand: 'SonicLab',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800',
    ],
    specifications: [
      { key: 'Power Output', value: '140W RMS Pair' },
      { key: 'Frequency Response', value: '38Hz - 22kHz' },
      { key: 'Inputs', value: 'XLR, 1/4" TRS, RCA' },
    ],
    stock: 12,
    model3D: { type: 'speaker', color: '#1e293b', accentColor: '#f59e0b', scale: 1.1 },
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Wave Portable Bluetooth Speaker',
    description: 'Rugged 360-degree outdoor speaker with deep punchy bass, RGB light halo, 24-hour battery, and power bank capability.',
    price: 129.99,
    discountPercentage: 20,
    categoryName: 'Audio & Acoustics',
    brand: 'SonicLab',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800',
    ],
    specifications: [
      { key: 'Battery', value: '10,000mAh (24 hrs)' },
      { key: 'Water Resistance', value: 'IP67 Dust & Water' },
    ],
    stock: 30,
    model3D: { type: 'speaker', color: '#ef4444', accentColor: '#f97316', scale: 1.0 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Clarity USB Studio Condenser Microphone',
    description: 'Cardioid studio condenser mic with zero-latency monitoring, onboard gain control, custom pop filter, and shock mount.',
    price: 149.50,
    discountPercentage: 5,
    categoryName: 'Audio & Acoustics',
    brand: 'AeroSound',
    images: [
      'https://images.unsplash.com/photo-1590658006821-04f4008d5717?w=800',
    ],
    specifications: [
      { key: 'Sample Rate', value: '24-bit / 96kHz' },
      { key: 'Capsule', value: '16mm Condenser' },
    ],
    stock: 18,
    model3D: { type: 'headphones', color: '#475569', accentColor: '#38bdf8', scale: 1.0 },
    isFeatured: false,
    isTrending: false,
  },

  // Category 2: Smart Wearables (Products 6-10)
  {
    name: 'Chronos Ultra GPS Smartwatch',
    description: 'Titanium outdoor GPS smartwatch with sapphire crystal lens, ECG monitoring, offline topographical maps, and 14-day battery life.',
    price: 449.99,
    discountPercentage: 12,
    categoryName: 'Smart Wearables',
    brand: 'Chronos',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800',
    ],
    specifications: [
      { key: 'Case Material', value: 'Grade 5 Titanium' },
      { key: 'Display', value: '1.4" AMOLED 1000 nits' },
      { key: 'Water Rating', value: '10 ATM (100m)' },
      { key: 'Sensors', value: 'ECG, SpO2, Dual GPS' },
    ],
    stock: 15,
    model3D: { type: 'watch', color: '#334155', accentColor: '#06b6d4', scale: 1.1 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Vibe Fit Health Band 5',
    description: 'Sleek lightweight activity tracker with continuous SpO2 monitoring, sleep scoring, female health tracking, and 100+ sports modes.',
    price: 79.99,
    discountPercentage: 25,
    categoryName: 'Smart Wearables',
    brand: 'Chronos',
    images: [
      'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800',
    ],
    specifications: [
      { key: 'Display', value: '1.1" Curved OLED' },
      { key: 'Battery', value: '10 Days Regular Use' },
    ],
    stock: 50,
    model3D: { type: 'watch', color: '#10b981', accentColor: '#34d399', scale: 0.9 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Aura Smart Ring Generation 3',
    description: 'Discreet titanium smart ring measuring body temperature variations, heart rate variability (HRV), sleep staging, and readiness index.',
    price: 299.00,
    discountPercentage: 0,
    categoryName: 'Smart Wearables',
    brand: 'Aura',
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    ],
    specifications: [
      { key: 'Material', value: 'PVD Coated Titanium' },
      { key: 'Weight', value: '4 to 6 grams' },
    ],
    stock: 20,
    model3D: { type: 'watch', color: '#f59e0b', accentColor: '#d97706', scale: 0.8 },
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Chronos Sport Active Watch',
    description: 'Vibrant sport smartwatch with aluminum chassis, interchangeable silicone bands, music storage, and automatic workout detection.',
    price: 199.99,
    discountPercentage: 15,
    categoryName: 'Smart Wearables',
    brand: 'Chronos',
    images: [
      'https://images.unsplash.com/photo-1544117519-31a4b719223d?w=800',
    ],
    specifications: [
      { key: 'Display', value: '1.3" Gorilla Glass' },
      { key: 'Storage', value: '4GB Onboard Music' },
    ],
    stock: 35,
    model3D: { type: 'watch', color: '#3b82f6', accentColor: '#60a5fa', scale: 1.0 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'Luxe Leather Smart Strap Chrono',
    description: 'Classic analog luxury timepiece with hidden OLED smart notification screen and genuine Italian leather strap.',
    price: 320.00,
    discountPercentage: 10,
    categoryName: 'Smart Wearables',
    brand: 'Aura',
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800',
    ],
    specifications: [
      { key: 'Movement', value: 'Swiss Quartz Hybrid' },
      { key: 'Strap', value: 'Top Grain Calf Leather' },
    ],
    stock: 14,
    model3D: { type: 'watch', color: '#78350f', accentColor: '#fbbf24', scale: 1.0 },
    isFeatured: false,
    isTrending: false,
  },

  // Category 3: Smartphones & Mobile (Products 11-15)
  {
    name: 'Titan Horizon Pro 5G Smartphone',
    description: 'Flagship smartphone featuring 6.8" 120Hz LTPO AMOLED display, 200MP quad camera setup, Snapdragon 8 Gen 3 processor, and 100W HyperCharge.',
    price: 1099.99,
    discountPercentage: 10,
    categoryName: 'Smartphones & Mobile',
    brand: 'TitanMobile',
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
      'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800',
    ],
    specifications: [
      { key: 'Display', value: '6.8" LTPO AMOLED 120Hz' },
      { key: 'Processor', value: 'Snapdragon 8 Gen 3' },
      { key: 'Camera', value: '200MP OIS + 50MP Periscope' },
      { key: 'RAM / Storage', value: '12GB / 512GB UFS 4.0' },
    ],
    stock: 18,
    model3D: { type: 'phone', color: '#0f172a', accentColor: '#38bdf8', scale: 1.2 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Nexus Edge Flip Foldable Phone',
    description: 'Next-gen foldable smartphone with seamless zero-gap hinge, dual AMOLED screens, IPX8 water resistance, and flex mode multitasking.',
    price: 1299.00,
    discountPercentage: 15,
    categoryName: 'Smartphones & Mobile',
    brand: 'Nexus',
    images: [
      'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800',
    ],
    specifications: [
      { key: 'Main Display', value: '7.6" Foldable Dynamic AMOLED' },
      { key: 'Cover Display', value: '6.2" HD+ 120Hz' },
    ],
    stock: 10,
    model3D: { type: 'phone', color: '#7c3aed', accentColor: '#c084fc', scale: 1.2 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Titan Lite 5G Smartphone',
    description: 'Sleek budget champion with 108MP camera, 5000mAh battery, 67W fast charger included, and vibrant 90Hz display.',
    price: 349.99,
    discountPercentage: 8,
    categoryName: 'Smartphones & Mobile',
    brand: 'TitanMobile',
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800',
    ],
    specifications: [
      { key: 'Battery', value: '5000mAh with 67W Turbo' },
      { key: 'Display', value: '6.5" FHD+ AMOLED' },
    ],
    stock: 45,
    model3D: { type: 'phone', color: '#2563eb', accentColor: '#60a5fa', scale: 1.0 },
    isFeatured: false,
    isTrending: false,
  },
  {
    name: 'UltraCharge 100W Magnetic Power Bank',
    description: 'Magnetic wireless power bank with digital battery percentage display, kickstand, and multi-device fast charging ports.',
    price: 69.99,
    discountPercentage: 15,
    categoryName: 'Smartphones & Mobile',
    brand: 'VoltGear',
    images: [
      'https://images.unsplash.com/photo-1609592424089-9a282f7d3fa9?w=800',
    ],
    specifications: [
      { key: 'Capacity', value: '15,000mAh' },
      { key: 'Wireless Output', value: '15W MagSafe Compatible' },
    ],
    stock: 60,
    model3D: { type: 'phone', color: '#475569', accentColor: '#10b981', scale: 0.9 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'ProGrip Mobile Gimbal Stabilizer',
    description: '3-axis motor gimbal for smartphones with AI face tracking, integrated tripod, extension rod, and magnetic clamp.',
    price: 139.99,
    discountPercentage: 10,
    categoryName: 'Smartphones & Mobile',
    brand: 'VoltGear',
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800',
    ],
    specifications: [
      { key: 'Stabilization', value: '3-Axis Active Motors' },
      { key: 'Battery Life', value: '12 Hours Continuous' },
    ],
    stock: 22,
    model3D: { type: 'phone', color: '#1e293b', accentColor: '#f43f5e', scale: 1.0 },
    isFeatured: false,
    isTrending: false,
  },

  // Category 4: Gaming & Computing (Products 16-20)
  {
    name: 'Vortex Elite Wireless Gaming Controller',
    description: 'Pro-grade wireless controller with hall effect anti-drift thumbsticks, mechanical tactile switches, customizable rear paddles, and RGB ambient glow.',
    price: 159.99,
    discountPercentage: 12,
    categoryName: 'Gaming & Computing',
    brand: 'VortexGaming',
    images: [
      'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800',
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800',
    ],
    specifications: [
      { key: 'Thumbsticks', value: 'Hall Effect Electromagnetic' },
      { key: 'Polling Rate', value: '1000Hz Low Latency' },
      { key: 'Battery', value: '40 Hours Rechargeable' },
      { key: 'Compatibility', value: 'PC, Switch, iOS, Android' },
    ],
    stock: 28,
    model3D: { type: 'controller', color: '#0f172a', accentColor: '#a855f7', scale: 1.1 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'CyberBlade RGB Mechanical Keyboard',
    description: 'Hot-swappable gasket-mounted mechanical keyboard with pre-lubed linear switches, PBT double-shot keycaps, and customizable OLED status screen.',
    price: 179.50,
    discountPercentage: 15,
    categoryName: 'Gaming & Computing',
    brand: 'VortexGaming',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    ],
    specifications: [
      { key: 'Form Factor', value: '75% Compact Layout' },
      { key: 'Switches', value: 'Linear Custom Lubed' },
      { key: 'Keycaps', value: 'South-facing PBT' },
    ],
    stock: 22,
    model3D: { type: 'controller', color: '#1e1b4b', accentColor: '#ec4899', scale: 1.0 },
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Spectra Precision Wireless Gaming Mouse',
    description: 'Ultralight 49g wireless gaming mouse equipped with 32,000 DPI optical sensor, optical switches, and 8,000Hz polling rate support.',
    price: 119.99,
    discountPercentage: 10,
    categoryName: 'Gaming & Computing',
    brand: 'VortexGaming',
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800',
    ],
    specifications: [
      { key: 'Weight', value: '49 Grams' },
      { key: 'Sensor', value: '32,000 DPI PAW3395' },
    ],
    stock: 35,
    model3D: { type: 'controller', color: '#0284c7', accentColor: '#38bdf8', scale: 0.9 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'VisionPro 32" Curved 4K 240Hz Monitor',
    description: 'Ultrawide QD-OLED gaming monitor delivering 0.03ms response time, VESA DisplayHDR True Black 400, and G-Sync compatibility.',
    price: 999.00,
    discountPercentage: 5,
    categoryName: 'Gaming & Computing',
    brand: 'PixelVision',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800',
    ],
    specifications: [
      { key: 'Panel', value: 'QD-OLED 1800R Curved' },
      { key: 'Resolution', value: '3840 x 2160 UHD' },
      { key: 'Refresh Rate', value: '240Hz / 0.03ms' },
    ],
    stock: 8,
    model3D: { type: 'controller', color: '#0f172a', accentColor: '#e11d48', scale: 1.3 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'AeroStream HD Streaming Web Cam',
    description: '4K HDR webcam with dual stereo microphones, auto-focus lens, magnetic privacy shutter, and built-in ring light.',
    price: 89.99,
    discountPercentage: 20,
    categoryName: 'Gaming & Computing',
    brand: 'PixelVision',
    images: [
      'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800',
    ],
    specifications: [
      { key: 'Resolution', value: '4K @ 30FPS / 1080P @ 60FPS' },
      { key: 'Field of View', value: '90-degree wide angle' },
    ],
    stock: 40,
    model3D: { type: 'controller', color: '#334155', accentColor: '#10b981', scale: 0.8 },
    isFeatured: false,
    isTrending: false,
  },

  // Category 5: Footwear & Performance (Products 21-25)
  {
    name: 'Strider Nitro Carbon Running Shoes',
    description: 'High-performance marathon shoe featuring full-length carbon fiber plate, nitrogen-infused foam midsole, and breathable engineered mesh upper.',
    price: 229.99,
    discountPercentage: 10,
    categoryName: 'Footwear & Performance',
    brand: 'Strider',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800',
    ],
    specifications: [
      { key: 'Midsole', value: 'Nitrogen-infused PEBA Foam' },
      { key: 'Plate', value: '3D Full Carbon Fiber' },
      { key: 'Weight', value: '198g (Men\'s 9)' },
      { key: 'Drop', value: '8mm' },
    ],
    stock: 30,
    model3D: { type: 'shoe', color: '#ef4444', accentColor: '#fcd34d', scale: 1.1 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'UrbanGlide Streetwear Sneakers',
    description: 'Modern lifestyle sneaker crafted from recycled ocean plastic mesh, responsive cushioned sole, and reflective accents.',
    price: 139.50,
    discountPercentage: 15,
    categoryName: 'Footwear & Performance',
    brand: 'Strider',
    images: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800',
    ],
    specifications: [
      { key: 'Upper Material', value: '100% Recycled Knit Fabric' },
      { key: 'Outsole', value: 'High-traction rubber' },
    ],
    stock: 25,
    model3D: { type: 'shoe', color: '#3b82f6', accentColor: '#93c5fd', scale: 1.0 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'TrailBlazer Waterproof Hiking Boots',
    description: 'Rugged waterproof hiking boot with Vibram rubber outsole, TPU shank support, and reinforced toe cap.',
    price: 189.99,
    discountPercentage: 5,
    categoryName: 'Footwear & Performance',
    brand: 'ApexGear',
    images: [
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800',
    ],
    specifications: [
      { key: 'Membrane', value: 'Gore-Tex Waterproof' },
      { key: 'Outsole', value: 'Vibram Megagrip' },
    ],
    stock: 18,
    model3D: { type: 'shoe', color: '#78350f', accentColor: '#d97706', scale: 1.1 },
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'FlexTrain Cross-Training Shoes',
    description: 'Versatile gym training shoes engineered for heavy lifting stability, plyometrics flexibility, and heel lockdown.',
    price: 124.99,
    discountPercentage: 12,
    categoryName: 'Footwear & Performance',
    brand: 'Strider',
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800',
    ],
    specifications: [
      { key: 'Heel Drop', value: '4mm Flat Base' },
      { key: 'Rope Wrap', value: 'Medial Rubber Grip' },
    ],
    stock: 35,
    model3D: { type: 'shoe', color: '#10b981', accentColor: '#6ee7b7', scale: 1.0 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'CloudWalk Recovery Slides',
    description: 'Ultra-plush EVA recovery sandals designed to relieve foot pressure and enhance post-workout recovery.',
    price: 49.99,
    discountPercentage: 0,
    categoryName: 'Footwear & Performance',
    brand: 'Strider',
    images: [
      'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800',
    ],
    specifications: [
      { key: 'Material', value: 'Dual-Density Molded EVA' },
      { key: 'Arch Support', value: 'Anatomic Orthotic Footbed' },
    ],
    stock: 50,
    model3D: { type: 'shoe', color: '#64748b', accentColor: '#cbd5e1', scale: 0.9 },
    isFeatured: false,
    isTrending: false,
  },

  // Category 6: Smart Home & Living (Products 26-30)
  {
    name: 'ErgoPro Mesh Executive Chair',
    description: 'Ergonomic lumbar support office chair with 4D adjustable armrests, dynamic mesh backrest, tilt lock mechanism, and heavy-duty aluminum base.',
    price: 389.99,
    discountPercentage: 18,
    categoryName: 'Smart Home & Living',
    brand: 'ErgoTech',
    images: [
      'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?w=800',
      'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800',
    ],
    specifications: [
      { key: 'Mesh Material', value: 'Breathable Korean Elastomer' },
      { key: 'Armrests', value: '4D Height, Depth, Pivot & Angle' },
      { key: 'Weight Limit', value: '350 lbs (158 kg)' },
      { key: 'Recline Angle', value: '90 - 135 degrees' },
    ],
    stock: 12,
    model3D: { type: 'chair', color: '#1e293b', accentColor: '#0284c7', scale: 1.1 },
    isFeatured: true,
    isTrending: true,
  },
  {
    name: 'Lumina Smart RGB Desk Lamp',
    description: 'Sleek architectural LED desk lamp with wireless smartphone charging pad, color temperature adjustment (2700K - 6500K), and ambient lighting modes.',
    price: 99.50,
    discountPercentage: 10,
    categoryName: 'Smart Home & Living',
    brand: 'LuminaHome',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
    ],
    specifications: [
      { key: 'Brightness', value: '1200 Lumens Max' },
      { key: 'Charger', value: '15W Wireless Qi' },
    ],
    stock: 40,
    model3D: { type: 'chair', color: '#e2e8f0', accentColor: '#f59e0b', scale: 0.9 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'AeroPure HEPA Smart Air Purifier',
    description: 'True HEPA H13 air purifier with real-time PM2.5 display, active carbon odor filter, silent night mode, and mobile app voice controls.',
    price: 199.99,
    discountPercentage: 15,
    categoryName: 'Smart Home & Living',
    brand: 'LuminaHome',
    images: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
    ],
    specifications: [
      { key: 'CADR', value: '400 m³/h' },
      { key: 'Room Coverage', value: 'Up to 500 sq ft' },
    ],
    stock: 22,
    model3D: { type: 'chair', color: '#0f172a', accentColor: '#10b981', scale: 1.0 },
    isFeatured: true,
    isTrending: false,
  },
  {
    name: 'Zenith Motorized Standing Desk 60x30"',
    description: 'Dual-motor electric standing desk with memory presets, solid bamboo tabletop, anti-collision sensor, and cable management tray.',
    price: 499.00,
    discountPercentage: 8,
    categoryName: 'Smart Home & Living',
    brand: 'ErgoTech',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800',
    ],
    specifications: [
      { key: 'Desktop Size', value: '60" x 30" Solid Bamboo' },
      { key: 'Height Range', value: '25" to 50.5"' },
    ],
    stock: 9,
    model3D: { type: 'chair', color: '#b45309', accentColor: '#fcd34d', scale: 1.2 },
    isFeatured: false,
    isTrending: true,
  },
  {
    name: 'AromaDiffuser Smart Essential Oil Nebulizer',
    description: 'Waterless smart essential oil diffuser with ambient mood lighting, timer schedule, and ultra-quiet cold air misting.',
    price: 64.99,
    discountPercentage: 20,
    categoryName: 'Smart Home & Living',
    brand: 'LuminaHome',
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800',
    ],
    specifications: [
      { key: 'Coverage', value: '400 sq ft' },
      { key: 'Noise Level', value: '< 25 dB' },
    ],
    stock: 35,
    model3D: { type: 'chair', color: '#ec4899', accentColor: '#f472b6', scale: 0.8 },
    isFeatured: false,
    isTrending: false,
  },
];

const sampleReviews = [
  {
    rating: 5,
    title: 'Outstanding Spatial Sound & Battery Life!',
    comment: 'The active noise cancellation on these Apex ANC headphones blew me away. I work in a noisy cafe daily and I can barely hear anything when music is playing. The 3D model viewer on SmartCart gave me a perfect preview before buying!',
  },
  {
    rating: 5,
    title: 'Titanium build feels truly indestructible',
    comment: 'Bought the Chronos Ultra smartwatch for hiking. The dual-band GPS is spot on, battery lasts over a week on a single charge. Highly recommend!',
  },
  {
    rating: 4,
    title: 'Incredible speed and camera clarity',
    comment: 'Titan Horizon Pro handles every heavy mobile game with 60+ FPS easily. The 200MP camera produces stunning portrait photos. Delivery was super fast.',
  },
  {
    rating: 5,
    title: 'No more thumbstick drift!',
    comment: 'The hall effect sticks on the Vortex controller feel smooth as silk. The back paddles are crisp and comfortable for long FPS gaming sessions.',
  },
  {
    rating: 5,
    title: 'Shaved 2 minutes off my 10K time!',
    comment: 'The carbon fiber plate in these Strider Nitro running shoes gives such incredible energy return. Lightweight and responsive.',
  },
];

module.exports = {
  categories,
  products,
  sampleReviews,
};
